#!/bin/bash

# Go through each directory in the root
for dir in */ ; do
  # Remove trailing slash to get the folder name
  folder_name="${dir%/}"

  # Prepare the content with the folder name injected
  cat > "${dir}README.md" <<EOF
# fullstack-projects
my junior fullstack projects
## HTML_CSS_JS_Basics/${folder_name}

### Try Out
<a href="https://marslinoed.github.io/fullstack-projects/HTML_CSS_JS_Basics/${folder_name}" target="_blank">
  <img src="../../try-it-out.svg" alt="Try it live"> 
</a>
EOF

  echo "README.md created in $dir"
done

